[API_KEYS]
OPENAI = ""
GROQ = "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"
ANTHROPIC = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://searxng:8080"

[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"
